// SPDX-License-Identifier: Apache-2.0
// Author: Jiuyang Liu <liu@jiuyang.me>

// Essentially, this package should be generated by tablegen,
// Before MLIR being able to template a Scala package.
// we should maintain it manually.
// This file is implemented based on 39c09035
package firrtl.backends.experimental.mlir

package object ops {
  type Block = Seq[Op]

  abstract class Node {
    def serialize: String = "todo"
  }

  trait Type extends Node

  trait Op extends Node

// defined in FIRRTLDialect.td
  trait FIRRTLOp extends Op

  /** [[PortInfo]] is defined in FIRRTLOpInferface.h file(not implemented with tablegen). */
  case class PortInfo(
    name:        StringAttr,
    tpe:         FIRRTLType,
    direction:   Direction,
    sym:         StringAttr,
    loc:         Location,
    annotations: AnnotationSet)

  /** Defined in FIRRTLAttributes.h */
  case object In extends Direction {
    def name:  String = "in"
    def value: Int = 0
  }
  case object Out extends Direction {
    def name:  String = "out"
    def value: Int = 1
  }
  trait Direction extends Enum
}