pull_request_rules:
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews:

pull_request_rules:
  - name: automatic squash-and-merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - base=master
      - label="Please Merge"
      - label!="DO NOT MERGE"
      - label!="bp-conflict"
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: merge

  - name: backport to 1.3.x
    conditions:
      - merged
      - base=master
      - milestone=1.3.x
    actions:
      backport:
        branches:
          - 1.3.x
        ignore_conflicts: True
        label_conflicts: "bp-conflict"
      label:
        add: [Backported]

  - name: label Mergify backport PR
    conditions:
      - base=1.3.x
      - body~=This is an automated backport of pull request \#\d+ done by Mergify
    actions:
      label:
        add: [Backport]

  - name: automatic squash-and-merge of backport PRs
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#changes-requested-reviews-by=0"
      - base=1.3.x
      - label="Backport"
      - label!="DO NOT MERGE"
      - label!="bp-conflict"
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: merge
