language: scala
scala:
  - 2.11.11
  - 2.12.3
sudo: false

cache:
  directories:
    $HOME/.ivy2
    $INSTALL_DIR

git:
  depth: 10

sbt_args: -Dsbt.log.noformat=true ++$TRAVIS_SCALA_VERSION

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin

before_script:
  - bash .install_verilator.sh
  - verilator --version

jobs:
  include:
    - stage: Test
    - &test
      script:
        # FIRRTL Tests
        - cd $TRAVIS_BUILD_DIR
        - sbt clean test
    - <<: *test
      script:
        - cd $TRAVIS_BUILD_DIR
        - sbt clean assembly publish-local
        - bash .run_chisel_tests.sh
