language: minimal
scala:
  - 2.12.11

services:
  - docker

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

sctipt:
  bash rundocker.sh

after_script:
  - pwd

cache:
  bundler: true
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/docker

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter="dangling=false" --format "{{.Repository}}:{{.Tag}} {{.ID}}"
    | xargs -n 2 -t sh -c "test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz"
