addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"        % "0.7.0")
addSbtPlugin("com.eed3si9n"     % "sbt-unidoc"           % "0.4.1")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.6")
addSbtPlugin("com.simplytyped"  % "sbt-antlr4"           % "0.8.1")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
